using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace NameReader.ArticleData.Helpers
{
    // 
    // This source code was auto-generated by xsd, Version=4.0.30319.17929.
    // 

    /// <summary>
    /// Generated from an RDF response.  This RDF response was then put in an XML file and VS2012 was used to extract a schema, this produced several XSD files which were combined
    /// (using XML Schema Definition Tool (Xsd.exe) http://msdn.microsoft.com/en-us/library/x6c1kb0s(v=vs.71).aspx) into CLR classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.w3.org/1999/02/22-rdf-syntax-ns#")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.w3.org/1999/02/22-rdf-syntax-ns#", IsNullable = false)]
    public partial class RDF
    {

        private RDFDescription[] descriptionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Description")]
        public RDFDescription[] Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.w3.org/1999/02/22-rdf-syntax-ns#")]
    public partial class RDFDescription
    {
        /// <summary>
        /// person common name
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("commonname", typeof(string), Namespace = "http://s.opencalais.com/1/pred/")]
        public string docPersonCommonName { get; set; }

        /// <summary>
        /// document category
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("categoryName", typeof(string), Namespace = "http://s.opencalais.com/1/pred/")]
        public string docCategoryName { get; set; }

        /// <summary>
        /// full document text
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("document", typeof(string), Namespace = "http://s.opencalais.com/1/pred/")]
        public string docFullDocument { get; set; }
    }
}
